const countryToContinentMap = {
    'ALG': 'Africa', 'ANG': 'Africa', 'BEN': 'Africa', 'BOT': 'Africa', 'BUR': 'Africa',
    'BDI': 'Africa', 'CMR': 'Africa', 'CPV': 'Africa', 'CAF': 'Africa', 'CHA': 'Africa',
    'COM': 'Africa', 'CGO': 'Africa', 'COD': 'Africa', 'CIV': 'Africa', 'DJI': 'Africa',
    'EGY': 'Africa', 'GEQ': 'Africa', 'ERI': 'Africa', 'SWZ': 'Africa', 'ETH': 'Africa',
    'GAB': 'Africa', 'GAM': 'Africa', 'GHA': 'Africa', 'GUI': 'Africa', 'GBS': 'Africa',
    'KEN': 'Africa', 'LES': 'Africa', 'LBR': 'Africa', 'LBA': 'Africa', 'MAD': 'Africa',
    'MAW': 'Africa', 'MLI': 'Africa', 'MTN': 'Africa', 'MRI': 'Africa', 'MAR': 'Africa',
    'MOZ': 'Africa', 'NAM': 'Africa', 'NIG': 'Africa', 'NGR': 'Africa', 'RWA': 'Africa',
    'STP': 'Africa', 'SEN': 'Africa', 'SEY': 'Africa', 'SLE': 'Africa', 'SOM': 'Africa',
    'RSA': 'Africa', 'SSD': 'Africa', 'SUD': 'Africa', 'TAN': 'Africa', 'TOG': 'Africa',
    'TUN': 'Africa', 'UGA': 'Africa', 'ZAM': 'Africa', 'ZIM': 'Africa',
    'AFG': 'Asia', 'BRN': 'Asia', 'BAN': 'Asia', 'BHU': 'Asia', 'BRU': 'Asia',
    'CAM': 'Asia', 'CHN': 'Asia', 'TPE': 'Asia', 'HKG': 'Asia', 'IND': 'Asia',
    'INA': 'Asia', 'IRI': 'Asia', 'IRQ': 'Asia', 'ISR': 'Asia', 'JPN': 'Asia',
    'JOR': 'Asia', 'KAZ': 'Asia', 'PRK': 'Asia', 'KOR': 'Asia', 'KUW': 'Asia',
    'KGZ': 'Asia', 'LAO': 'Asia', 'LBN': 'Asia', 'MAS': 'Asia', 'MDV': 'Asia',
    'MGL': 'Asia', 'MYA': 'Asia', 'NEP': 'Asia', 'OMA': 'Asia', 'PAK': 'Asia',
    'PLE': 'Asia', 'PHI': 'Asia', 'QAT': 'Asia', 'KSA': 'Asia', 'SIN': 'Asia',
    'SRI': 'Asia', 'SYR': 'Asia', 'TJK': 'Asia', 'THA': 'Asia', 'TLS': 'Asia',
    'TKM': 'Asia', 'UAE': 'Asia', 'UZB': 'Asia', 'VIE': 'Asia', 'YEM': 'Asia',
    'ALB': 'Europe', 'AND': 'Europe', 'ARM': 'Europe', 'AUT': 'Europe', 'AZE': 'Europe',
    'BLR': 'Europe', 'BEL': 'Europe', 'BIH': 'Europe', 'BUL': 'Europe', 'CRO': 'Europe',
    'CYP': 'Europe', 'CZE': 'Europe', 'DEN': 'Europe', 'EST': 'Europe', 'FIN': 'Europe',
    'FRA': 'Europe', 'GEO': 'Europe', 'GER': 'Europe', 'GBR': 'Europe', 'GRE': 'Europe',
    'HUN': 'Europe', 'ISL': 'Europe', 'IRL': 'Europe', 'ITA': 'Europe', 'LAT': 'Europe',
    'LIE': 'Europe', 'LTU': 'Europe', 'LUX': 'Europe', 'MKD': 'Europe', 'MLT': 'Europe',
    'MDA': 'Europe', 'MON': 'Europe', 'MNE': 'Europe', 'NED': 'Europe', 'NOR': 'Europe',
    'POL': 'Europe', 'POR': 'Europe', 'ROU': 'Europe', 'RUS': 'Europe', 'SMR': 'Europe',
    'SRB': 'Europe', 'SVK': 'Europe', 'SLO': 'Europe', 'ESP': 'Europe', 'SWE': 'Europe',
    'SUI': 'Europe', 'TUR': 'Europe', 'UKR': 'Europe', 'EUN': 'Europe', 'URS': 'Europe',
    'TCH': 'Europe', 'YUG': 'Europe',
    'ANT': 'North America', 'ARU': 'North America', 'BAH': 'North America', 'BAR': 'North America',
    'BIZ': 'North America', 'BER': 'North America', 'CAN': 'North America', 'CAY': 'North America',
    'CRC': 'North America', 'CUB': 'North America', 'DMA': 'North America', 'DOM': 'North America',
    'ESA': 'North America', 'GRN': 'North America', 'GUM': 'North America', 'GUA': 'North America',
    'HAI': 'North America', 'HON': 'North America', 'JAM': 'North America', 'MEX': 'North America',
    'NCA': 'North America', 'PAN': 'North America', 'PUR': 'North America', 'SKN': 'North America',
    'LCA': 'North America', 'VIN': 'North America', 'TTO': 'North America', 'USA': 'North America',
    'ISV': 'North America',
    'ARG': 'South America', 'BOL': 'South America', 'BRA': 'South America', 'CHI': 'South America',
    'COL': 'South America', 'ECU': 'South America', 'GUY': 'South America', 'PAR': 'South America',
    'PER': 'South America', 'SUR': 'South America', 'URU': 'South America', 'VEN': 'South America',
    'ASA': 'Oceania', 'AUS': 'Oceania', 'COK': 'Oceania', 'FIJ': 'Oceania', 'FSM': 'Oceania',
    'KIR': 'Oceania', 'MHL': 'Oceania', 'NRU': 'Oceania', 'NZL': 'Oceania', 'PLW': 'Oceania',
    'PNG': 'Oceania', 'SAM': 'Oceania', 'SOL': 'Oceania', 'TGA': 'Oceania', 'TUV': 'Oceania',
    'VAN': 'Oceania'
};
const continentColors = {
    'Africa': '#1f77b4',
    'Asia': '#ff7f0e',
    'Europe': '#2ca02c',
    'North America': '#d62728',
    'South America': '#9467bd',
    'Oceania': '#8c564b',
    'Other': '#e377c2'
};
